const PAGES = {
  personalArea: "personalarea",
  login: "login",
  entryApp: "/",
  editHome: "home",
  editGeneral: "general",
  editAbout: "about",
  editSupportUs: "supportUs",
  editFaq: "faq",
  editorFaq: "editorFaq",
  editSocial: "social",
  editorSocial: "editorSocial",
  events: "events",
  editorEvents: "editorEvents",
  articlesBlog: "blog",
  editorBlog: "editorBlog",
  articlesCategories: "categories",
  usersCollaborators: "collaborators",
  editorCollaborators: "editorCollaborators",
  usersVolunteers: "volunteers",
  editorVolunteers: "editorVolunteers",
  donations: "donations",
};
export default PAGES;
