const PAGES = {
  personalArea: "/backoffice/personalarea",
  login: "/",
  entryApp: "backoffice",
  editHome: "/backoffice/home",
  editGeneral: "/backoffice/general",
  editAbout: "/backoffice/about",
  editSupportUs: "/backoffice/supportUs",
  editFaq: "/backoffice/faq",
  editorFaq: "/backoffice/editorFaq",
  editSocial: "/backoffice/social",
  editorSocial: "/backoffice/editorSocial",
  events: "/backoffice/events",
  editorEvents: "/backoffice/editorEvents",
  articlesBlog: "/backoffice/blog",
  editorBlog: "/backoffice/editorBlog",
  articlesCategories: "/backoffice/categories",
  usersCollaborators: "/backoffice/collaborators",
  editorCollaborators: "/backoffice/editorCollaborators",
  usersVolunteers: "/backoffice/volunteers",
  editorVolunteers: "/backoffice/editorVolunteers",
  donations: "/backoffice/donations",
};
export default PAGES;
