const APIROUTES = {
  ABOUT: "/about",
  ABOUTUPDATE: "/about/update-about",
  ABOUTADD: "/about/save-about",
  ARTICLE: "/article/",
  ARTICLEADD: "article/add",
  SIGNIN: "/signin",
  CATEGORY: "/category",
  CATEGORYADD: "/category/add",
  EVENTS: "/event/list-events",
  EVENTSINGLE: "/event",
  EVENTSADD: "/event/new-event",
  EVENTSUPDATE: "/event/edit-event",
  EVENTSDELETE: "/event/delete-event",
  GENERAL: "/customization",
  GENERALPUT: "/customization/update-customization",
  DONATION: "donation/all",
  DONATIONAMOUNT: "donation/amount/all",
  FAQ: "/faq",
  FAQHANDLE: "/faq/question",
  INFOPUT: "/faq/info",
  SOCIAL: "/social",
  SOCIALSINGLE: "/social/by-id",
  SOCIALADD: "/social/save",
  SOCIALDELETE: "/social/delete",
  SOCIALUPDATE: "/social/update",
  SUPPORTUS: "/support",
  SUPPORTADD: "/support/save-support/",
  SUPPORTUSUPDATE: "/support/update-support",
  USER: "/user",
  COLLABORATORS: "user/collaborators",
  ACTIVECOLLABORATORS: "user/active-collaborators",
  DEACTIVATEDCOLLABORATORS: "user/deactivated-collaborators",
  GUEST: "user/guest",
  ACTIVEGUESTS: "user/active-guests",
  DEACTIVATEDGUESTS: "user/deactivated-guests",
  USERADD: "user/signup",
  HOME: "/home",
  HOMEEDIT: "/home/new-home",
};

export default APIROUTES;
